Site/WebApplication1/WebApplication1/Models/Entities/ConsaltantRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Models
{
    public class ConsaltantRequest:BaseEntity
    {
        [Display(Name="نام")]
        public string FullName { get; set; }

        [Display(Name = "ایمیل")]
        public string Email { get; set; }
        [Display(Name = "موضوع")]
        public string Subject { get; set; }

        [Display(Name = "شماره موبایل")]
        public string CellNumber { get; set; }
        [Display(Name = "متن درخواست")]
        [DataType(DataType.MultilineText)]
        public string Body { get; set; }
        [Display(Name = "پاسخ درخواست")]
        [DataType(DataType.MultilineText)]
        public string Response { get; set; }
    }
}

Site/WebApplication1/WebApplication1/Controllers/ConsaltantRequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Models;

namespace WebApplication1.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ConsaltantRequestsController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: ConsaltantRequests
        public ActionResult Index()
        {
            return View(db.ConsaltantRequests.Where(a=>a.IsDeleted==false).OrderByDescending(a=>a.CreationDate).ToList());
        }

        // GET: ConsaltantRequests/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ConsaltantRequest consaltantRequest = db.ConsaltantRequests.Find(id);
            if (consaltantRequest == null)
            {
                return HttpNotFound();
            }
            return View(consaltantRequest);
        }

        // GET: ConsaltantRequests/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ConsaltantRequests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FullName,Email,Subject,CellNumber,Body,Response,IsActive,CreationDate,LastModifiedDate,IsDeleted,DeletionDate,Description")] ConsaltantRequest consaltantRequest)
        {
            if (ModelState.IsValid)
            {
				consaltantRequest.IsDeleted=false;
				consaltantRequest.CreationDate= DateTime.Now; 
                consaltantRequest.Id = Guid.NewGuid();
                db.ConsaltantRequests.Add(consaltantRequest);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(consaltantRequest);
        }

        // GET: ConsaltantRequests/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ConsaltantRequest consaltantRequest = db.ConsaltantRequests.Find(id);
            if (consaltantRequest == null)
            {
                return HttpNotFound();
            }
            return View(consaltantRequest);
        }

        // POST: ConsaltantRequests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FullName,Email,Subject,CellNumber,Body,Response,IsActive,CreationDate,LastModifiedDate,IsDeleted,DeletionDate,Description")] ConsaltantRequest consaltantRequest)
        {
            if (ModelState.IsValid)
            {
				consaltantRequest.IsDeleted = false;
				consaltantRequest.LastModifiedDate = DateTime.Now;
                db.Entry(consaltantRequest).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(consaltantRequest);
        }

        // GET: ConsaltantRequests/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ConsaltantRequest consaltantRequest = db.ConsaltantRequests.Find(id);
            if (consaltantRequest == null)
            {
                return HttpNotFound();
            }
            return View(consaltantRequest);
        }

        // POST: ConsaltantRequests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            ConsaltantRequest consaltantRequest = db.ConsaltantRequests.Find(id);
			consaltantRequest.IsDeleted=true;
			consaltantRequest.DeletionDate=DateTime.Now;
 
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [AllowAnonymous]
        public ActionResult SubmitRequest(string fullName, string subject, string cellNumber, string email, string message)
        {
            try
            {
                ConsaltantRequest request = new ConsaltantRequest()
                {
                    CreationDate = DateTime.Now,
                    IsDeleted = false,
                    Id = Guid.NewGuid(),
                    CellNumber = cellNumber,
                    IsActive = false,
                    Body = message,
                    FullName = fullName,
                    Email = email,
                    Subject = subject
                };

                db.ConsaltantRequests.Add(request);
                db.SaveChanges();
                return Json("true", JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json("false", JsonRequestBehavior.AllowGet);
            }
        }

    }
}

Site/WebApplication1/WebApplication1/Views/ConsaltantRequests/Create.cshtml
@model Models.ConsaltantRequest

@{
    ViewBag.Title = "افزودن " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>افزودن @Html.DisplayNameFor(model => model)</h2>

@using (Html.BeginForm("Create", "ConsaltantRequests",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        @Html.ValidationSummary(true)

        <div class="form-group">
        <div class="form-group">
            @Html.LabelFor(model => model.FullName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.FullName)

                @Html.ValidationMessageFor(model => model.FullName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.Email)

                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.Subject)

                @Html.ValidationMessageFor(model => model.Subject)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CellNumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.CellNumber)

                @Html.ValidationMessageFor(model => model.CellNumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.Body)

                @Html.ValidationMessageFor(model => model.Body)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Response, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.Response)

                @Html.ValidationMessageFor(model => model.Response)
            </div>
        </div>

        <div class="form-group">
			<div class="col-md-2">
            </div>
            <div class="col-md-10">
                    @Html.EditorFor(model => model.IsActive)

				@Html.LabelFor(model => model.IsActive)
                @Html.ValidationMessageFor(model => model.IsActive)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.Description)

                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group" id="buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ایجاد" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
            </div>
        </div>
        </div>
</div>
}

Site/WebApplication1/WebApplication1/Views/ConsaltantRequests/Delete.cshtml
@model Models.ConsaltantRequest

@{
    ViewBag.Title = "حذف " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

<h3>آیا از حذف این مورد اطمینان دارید؟</h3>
<div>    
    <hr />
    <div class="form-horizontal">        
    
         <div class="form-group">
            @Html.LabelFor(model => model.FullName, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.FullName)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Email)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Subject, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Subject)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.CellNumber, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.CellNumber)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Body, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Body)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Response, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Response)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.IsActive)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.CreationDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.CreationDate)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.LastModifiedDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.LastModifiedDate)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Description)
      </div></div>

  </div>  

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

       <div class="form-group" id="buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="تایید حذف" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
            </div>
        </div>
    }
</div>

Site/WebApplication1/WebApplication1/Views/ConsaltantRequests/Details.cshtml
@model Models.ConsaltantRequest

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ConsaltantRequest</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CellNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CellNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Response)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Response)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeletionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeletionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Site/WebApplication1/WebApplication1/Views/ConsaltantRequests/Edit.cshtml
@model Models.ConsaltantRequest

@{
    ViewBag.Title = "ویرایش " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "ConsaltantRequests",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.FullName)
                @Html.ValidationMessageFor(model => model.FullName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.Subject)
                @Html.ValidationMessageFor(model => model.Subject)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CellNumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.CellNumber)
                @Html.ValidationMessageFor(model => model.CellNumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.Body)
                @Html.ValidationMessageFor(model => model.Body)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Response, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.Response)
                @Html.ValidationMessageFor(model => model.Response)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.IsActive)
                @Html.ValidationMessageFor(model => model.IsActive)
            </div>
        </div>

	 @Html.HiddenFor(model => model.CreationDate)
        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group" id="buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ثبت" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
            </div>
        </div>
    </div>
}

Site/WebApplication1/WebApplication1/Views/ConsaltantRequests/Index.cshtml
@model IEnumerable<Models.ConsaltantRequest>

@{
ViewBag.Title = "فهرست درخواست ها" ;
    
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

        @(Html.Kendo().Grid(Model)
              .Name("Grid")
              .Columns(columns =>
                  {
                                columns.Bound(model => model.FullName);
        columns.Bound(model => model.Email);
        columns.Bound(model => model.Subject);
        columns.Bound(model => model.CellNumber);
        columns.Bound(model => model.IsActive);
        columns.Bound(model => model.CreationDate);
					columns.Bound(item => @item.Id).Title("دستورات").Filterable(false).Groupable(false)
							.Template(@<text>
									@Html.ActionLink("ویرایش", "Edit", new {id = @item.Id}, new {@class = "k-button"})
									@Html.ActionLink("حذف", "Delete", new {id = @item.Id}, new {@class = "k-button"})
									</text>).Width(200);  
		})
		.ToolBar(toolbar =>
					{				
						toolbar.Custom().Action("Create","ConsaltantRequests").Text("افزودن");                          
					}
		)         
		.DataSource(dataSource => dataSource
									.Server()
							
									.Model(model => model.Id(item => item.Id))
					)              
	)